# Generated by Django 3.0.9 on 2020-08-31 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_auto_20200831_0031'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'permissions': [('change_expense_status', 'Can change the status of expense'), ('can_view_approve_expense', 'Can view approved expenses')]},
        ),
    ]
